-- ARCANA · party de ejemplo
-- Generado por scripts/generate-seed.mjs a partir de src/data/defaults.ts.
-- No editar a mano: vuelve a lanzar el script si cambian los datos.
--
-- Ejecutar DESPUÉS de supabase/migrations/0001_init.sql.
-- Se puede lanzar varias veces: las filas ya existentes se ignoran.
--
-- owner_id queda a null a propósito: estos personajes son de la mesa, no de
-- una cuenta concreta, y todos los usuarios tienen los mismos permisos.

insert into public.characters (id, name, data) values
  ('a1000000-0000-4000-8000-000000000001', 'Kaelith Vroun', '{"id":"a1000000-0000-4000-8000-000000000001","createdAt":"2026-09-08T07:27:25.565Z","updatedAt":"2026-09-08T07:27:25.565Z","identity":{"name":"Kaelith Vroun","player":"","className":"Mago","subclass":"Evocación","level":3,"species":"Elfo","background":"Sabio","alignment":"Neutral","xp":0,"portrait":"assets/portraits/mago.svg","accent":"#3f7bd6","tagline":"La biblioteca arde y él sigue leyendo"},"abilities":{"str":8,"dex":14,"con":13,"int":17,"wis":12,"cha":10},"saves":{"str":0,"dex":0,"con":0,"int":1,"wis":1,"cha":0},"skills":{"acrobatics":0,"animalHandling":0,"arcana":1,"athletics":0,"deception":0,"history":1,"insight":0,"intimidation":0,"investigation":1,"medicine":0,"nature":0,"perception":0,"performance":0,"persuasion":0,"religion":0,"sleightOfHand":0,"stealth":0,"survival":0},"combat":{"armorClass":12,"speed":9,"initiativeBonus":0,"hpMax":20,"hpCurrent":20,"hpTemp":0,"hitDieSize":6,"hitDiceTotal":3,"hitDiceSpent":0,"deathSuccesses":0,"deathFailures":0,"heroicInspiration":false,"exhaustion":0,"conditions":[],"attacks":[]},"spellcasting":{"ability":"int","slots":[{"level":1,"total":4,"used":0},{"level":2,"total":2,"used":0}],"spells":[],"notes":""},"inventory":{"coins":{"pp":0,"gp":0,"ep":0,"sp":0,"cp":0},"items":[],"notes":""},"features":{"entries":[],"languages":["Común"],"armor":"","weapons":"","tools":""},"journal":{"personality":"","ideals":"","bonds":"","flaws":"","backstory":"","allies":"","notes":""}}'::jsonb),
  ('a1000000-0000-4000-8000-000000000002', 'Brann Hierroviejo', '{"id":"a1000000-0000-4000-8000-000000000002","createdAt":"2026-09-08T07:27:25.568Z","updatedAt":"2026-09-08T07:27:25.568Z","identity":{"name":"Brann Hierroviejo","player":"","className":"Bárbaro","subclass":"Senda del Berserker","level":3,"species":"Goliat","background":"Soldado","alignment":"Neutral","xp":0,"portrait":"assets/portraits/barbaro.svg","accent":"#e03a2f","tagline":"Habla poco. Rompe mucho."},"abilities":{"str":17,"dex":13,"con":16,"int":8,"wis":12,"cha":10},"saves":{"str":1,"dex":0,"con":1,"int":0,"wis":0,"cha":0},"skills":{"acrobatics":0,"animalHandling":0,"arcana":0,"athletics":1,"deception":0,"history":0,"insight":0,"intimidation":1,"investigation":0,"medicine":0,"nature":0,"perception":0,"performance":0,"persuasion":0,"religion":0,"sleightOfHand":0,"stealth":0,"survival":1},"combat":{"armorClass":15,"speed":9,"initiativeBonus":0,"hpMax":34,"hpCurrent":34,"hpTemp":0,"hitDieSize":12,"hitDiceTotal":3,"hitDiceSpent":0,"deathSuccesses":0,"deathFailures":0,"heroicInspiration":false,"exhaustion":0,"conditions":[],"attacks":[]},"spellcasting":{"ability":null,"slots":[],"spells":[],"notes":""},"inventory":{"coins":{"pp":0,"gp":0,"ep":0,"sp":0,"cp":0},"items":[],"notes":""},"features":{"entries":[],"languages":["Común"],"armor":"","weapons":"","tools":""},"journal":{"personality":"","ideals":"","bonds":"","flaws":"","backstory":"","allies":"","notes":""}}'::jsonb),
  ('a1000000-0000-4000-8000-000000000003', 'Nyx', '{"id":"a1000000-0000-4000-8000-000000000003","createdAt":"2026-09-08T07:27:25.568Z","updatedAt":"2026-09-08T07:27:25.568Z","identity":{"name":"Nyx","player":"","className":"Pícaro","subclass":"Ladrón","level":3,"species":"Tiefling","background":"Criminal","alignment":"Neutral","xp":0,"portrait":"assets/portraits/picaro.svg","accent":"#6f7cd1","tagline":"Nunca la viste entrar"},"abilities":{"str":10,"dex":17,"con":13,"int":13,"wis":12,"cha":14},"saves":{"str":0,"dex":1,"con":0,"int":1,"wis":0,"cha":0},"skills":{"acrobatics":0,"animalHandling":0,"arcana":0,"athletics":0,"deception":1,"history":0,"insight":0,"intimidation":0,"investigation":0,"medicine":0,"nature":0,"perception":1,"performance":0,"persuasion":0,"religion":0,"sleightOfHand":1,"stealth":1,"survival":0},"combat":{"armorClass":14,"speed":9,"initiativeBonus":0,"hpMax":21,"hpCurrent":21,"hpTemp":0,"hitDieSize":8,"hitDiceTotal":3,"hitDiceSpent":0,"deathSuccesses":0,"deathFailures":0,"heroicInspiration":false,"exhaustion":0,"conditions":[],"attacks":[]},"spellcasting":{"ability":null,"slots":[],"spells":[],"notes":""},"inventory":{"coins":{"pp":0,"gp":0,"ep":0,"sp":0,"cp":0},"items":[],"notes":""},"features":{"entries":[],"languages":["Común"],"armor":"","weapons":"","tools":""},"journal":{"personality":"","ideals":"","bonds":"","flaws":"","backstory":"","allies":"","notes":""}}'::jsonb),
  ('a1000000-0000-4000-8000-000000000004', 'Sor Maren', '{"id":"a1000000-0000-4000-8000-000000000004","createdAt":"2026-09-08T07:27:25.568Z","updatedAt":"2026-09-08T07:27:25.568Z","identity":{"name":"Sor Maren","player":"","className":"Clérigo","subclass":"Dominio de la Vida","level":3,"species":"Aasimar","background":"Acólito","alignment":"Neutral","xp":0,"portrait":"assets/portraits/clerigo.svg","accent":"#e8c15a","tagline":"La luz no pide permiso"},"abilities":{"str":13,"dex":10,"con":14,"int":11,"wis":17,"cha":13},"saves":{"str":0,"dex":0,"con":0,"int":0,"wis":1,"cha":1},"skills":{"acrobatics":0,"animalHandling":0,"arcana":0,"athletics":0,"deception":0,"history":0,"insight":1,"intimidation":0,"investigation":0,"medicine":1,"nature":0,"perception":0,"performance":0,"persuasion":0,"religion":1,"sleightOfHand":0,"stealth":0,"survival":0},"combat":{"armorClass":18,"speed":9,"initiativeBonus":0,"hpMax":24,"hpCurrent":24,"hpTemp":0,"hitDieSize":8,"hitDiceTotal":3,"hitDiceSpent":0,"deathSuccesses":0,"deathFailures":0,"heroicInspiration":false,"exhaustion":0,"conditions":[],"attacks":[]},"spellcasting":{"ability":"wis","slots":[{"level":1,"total":4,"used":0},{"level":2,"total":2,"used":0}],"spells":[],"notes":""},"inventory":{"coins":{"pp":0,"gp":0,"ep":0,"sp":0,"cp":0},"items":[],"notes":""},"features":{"entries":[],"languages":["Común"],"armor":"","weapons":"","tools":""},"journal":{"personality":"","ideals":"","bonds":"","flaws":"","backstory":"","allies":"","notes":""}}'::jsonb)
on conflict (id) do nothing;
