/**
 * Generates supabase/seed.sql from the example party defined in TypeScript
 * (src/data/defaults.ts), so there are never two versions of the same data.
 * Uses esbuild, which already ships with Vite.
 *
 *   node scripts/generate-seed.mjs
 */
import { build } from 'esbuild'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')

const bundle = await build({
  entryPoints: [resolve(root, 'src/data/defaults.ts')],
  bundle: true,
  write: false,
  format: 'esm',
  platform: 'neutral',
  alias: { '@': resolve(root, 'src') },
})

const code = bundle.outputFiles[0].text
const module = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`)

// Fixed ids: that way the seed can be re-run without duplicating anything.
const IDS = [
  'a1000000-0000-4000-8000-000000000001',
  'a1000000-0000-4000-8000-000000000002',
  'a1000000-0000-4000-8000-000000000003',
  'a1000000-0000-4000-8000-000000000004',
]

const roster = module.demoRoster().map((character, i) => ({
  ...character,
  id: IDS[i] ?? character.id,
}))

const quote = (value) => `'${String(value).replace(/'/g, "''")}'`

const rows = roster
  .map((c) => `  (${quote(c.id)}, ${quote(c.identity.name)}, ${quote(JSON.stringify(c))}::jsonb)`)
  .join(',\n')

const sql = `-- ARCANA · example party
-- Generated by scripts/generate-seed.mjs from src/data/defaults.ts.
-- Do not edit by hand: re-run the script if the data changes.
--
-- Run AFTER supabase/migrations/0001_init.sql.
-- Safe to run several times: rows that already exist are ignored.
--
-- owner_id is left null on purpose: these characters belong to the table, not
-- to one account, and every user has the same permissions.

insert into public.characters (id, name, data) values
${rows}
on conflict (id) do nothing;
`

mkdirSync(resolve(root, 'supabase'), { recursive: true })
writeFileSync(resolve(root, 'supabase/seed.sql'), sql)
console.log(`Wrote supabase/seed.sql with ${roster.length} characters.`)
